A DB pool `shutdown()` must close all the connections, including those just created.
Otherwise, the `env.get_known_users` test in source:trunk/trac/tests/env.py will fail on Windows:

{{{
...
    os.remove(fullname)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: '...\\trac-tempenv\\db\\trac.db'
}}}


git-svn-id: http://trac.edgewall.org/intertrac/log:/trunk@7208 af82e41b-90c4-0310-8c96-b1721e28e2e2